### ISSUE TITLE
replaceOne Method requested

### ISSUE THREAD

**Issue by klawson4311** [theryaz/veden-mongodb#1]
`let result = await db.collection(db_params.collection).update(query,body,{upsert: true});`

When `db_params.overwrite == true`, it removes the $set, thereby throwing the error:
`MongoError: the update operation document must contain atomic operators.` 

The upsert flag here just inserts the document if none matched the query.  This is likely undesirable..?

Suggestions:

1.  implement a replaceOne() method, or 
2.  when db_params.overwrite == true,  use replaceOne instead of updateOne()

**Comment by theryaz** [comment]
Implemented in [b043749](https://github.com/theryaz/veden-mongodb/commit/b04374902db182919f14420bbf50e132db7205d9)
